# Generated by Django 4.2.14 on 2024-07-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
