# Generated by Django 4.2.14 on 2024-07-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_category_alter_property_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='guests',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
