# Generated by Django 4.2.14 on 2024-07-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/uploads/categories/category_beach.svg', upload_to='uploads/categories'),
            preserve_default=False,
        ),
    ]
